### ISSUE TITLE
Add YandexGPT Summarizer

### ISSUE THREAD

**Issue by ede11** [NexonSU/telegram-go-chatbot#20]
[Summarizer](https://300.ya.ru) have free API

Example:

>>> import requests
>>> endpoint = 'https://300.ya.ru/api/sharing-url'
>>> response = requests.post(
    endpoint,
    json = {
      'article_url': 'https://habr.com/ru/news/729422/'
    },
    headers = {'Authorization': 'OAuth <token>'}
)
>>> response.json()
{
  "status": "success",
  "sharing_url": "https://300.ya.ru/3fOcYRBL"
}

**Comment by NexonSU** [comment]
https://github.com/NexonSU/telegram-go-chatbot/commit/01a2ea7407e750ff199d5909724bbb80ffd62921
